import ProviderWrapper from "@/providers/ProviderWrapper";
import type { Metadata } from "next";
import "./globals.css";
import "./normalize.css";

export const metadata: Metadata = {
  title: "Puffu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"
        />
        <meta name="theme-color" content="#000" />
        <meta name="robots" content="index,follow" />
      </head>
      <body>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
